### PR TITLE
Update latest bluebird and pg

### PR DESCRIPTION
**Pull request by mbrio**
Updated bluebird to 2 and PG to 4. I haven't had any issues with the results.

### CODE REVIEW

**Comment by Atsman** [comment]
Hi, 

when will you merge it?

**Comment by mbrio** [comment]
Unfortunately I am not able to do so as I am not an administrator on this project, we'll have to wait for one of them.

**Comment by Atsman** [comment]
@mbrio, i have already rewrote this module with native promises and create my own module :)

**Comment by lkaragol** [comment]
Sorry for latency and thank you.

**Pull request merged**
